version: '3'

services:
    #Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx_sf_api
        restart: unless-stopped
        tty: true
        ports:
            - "${PORT}:80"
        volumes:
            - ./docker-images/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
        networks:
            - sf-api-network
    api:
        build: ./
        container_name: sf-api
        # image: ${AWS_USER}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_REPO_NAME}
        networks:
            - sf-api-network
        # volumes:
        #     - ./:/api
        #     - /api/node_modules
        # ports:
        #     - '5000:5000'
networks:
    sf-api-network:
        driver: bridge